"""0001_create_chores_calendarevents

Revision ID: 564450e8dca4
Revises: 
Create Date: 2026-03-16 12:13:19.123238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564450e8dca4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('start_from', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='frequencychoices'), nullable=True),
    sa.Column('frequency_interval', sa.Integer(), nullable=True),
    sa.Column('rrules', sa.JSON(none_as_null=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=250), nullable=False),
    sa.Column('starts_from', sa.DateTime(), nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=True),
    sa.Column('is_parent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DONE', 'POSTPONED', 'CANCELED', name='statuschoices'), nullable=False),
    sa.Column('status_data', sa.JSON(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_events')
    op.drop_table('chores')
    # ### end Alembic commands ###
