"""0002_create_collection

Revision ID: 1ae95d98faa7
Revises: 564450e8dca4
Create Date: 2026-03-24 11:21:07.359078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae95d98faa7'
down_revision: Union[str, Sequence[str], None] = '564450e8dca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chores', 'frequency')
    op.drop_column('chores', 'frequency_interval')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('frequency_interval', sa.INTEGER(), nullable=True))
    op.add_column('chores', sa.Column('frequency', sa.VARCHAR(length=7), nullable=True))
    # ### end Alembic commands ###
