"""0003_create_assingee_add_relation_assignee_calendarevent

Revision ID: c1aa53fea8a7
Revises: 1ae95d98faa7
Create Date: 2026-03-24 15:05:27.450363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1aa53fea8a7'
down_revision: Union[str, Sequence[str], None] = '1ae95d98faa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignee')),
    sa.UniqueConstraint('email', name=op.f('uq_assignee_email')),
    sa.UniqueConstraint('name', name=op.f('uq_assignee_name'))
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_calendar_events_calendar_event_id'), ['calendar_event_id'])
        batch_op.create_foreign_key(batch_op.f('fk_calendar_events_assignee_id_assignee'), 'assignee', ['assignee_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_chores_name'), ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_chores_name'), type_='unique')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_calendar_events_assignee_id_assignee'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_calendar_events_calendar_event_id'), type_='unique')

    op.drop_table('assignee')
    # ### end Alembic commands ###
