"""0004_create_collection_add_relation_chore_collection

Revision ID: eaf30ab4500c
Revises: c1aa53fea8a7
Create Date: 2026-03-24 15:27:55.760456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf30ab4500c'
down_revision: Union[str, Sequence[str], None] = 'c1aa53fea8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('name', name=op.f('uq_collections_name'))
    )
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_chores_collection_id_collections'), 'collections', ['collection_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chores_collection_id_collections'), type_='foreignkey')
        batch_op.drop_column('collection_id')

    op.drop_table('collections')
    # ### end Alembic commands ###
